export const SET_MAIN_CATAGORY = "SET_MAIN_CATAGORY"

export const SET_PHONE = "SET_PHONE"

export const SET_TRENDING = "SET_TRENDING"

export const SEARCH_INPUT_VALUE = "SEARCH_INPUT_VALUE"

export const SEARCHED_ITEM = "SEARCHED_ITEM"

export const RANGE_VALUE = "RANGE_VALUE"

export const INDIVIDUAL_ITEM = "INDIVIDUAL_ITEM"

export const ADD_TO_CART = "ADD_TO_CART"